substitutions:
  device_name: bedroom_blind
  friendly_name: Bedroom Blind

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret ip_bedroom_blind
    gateway: 192.168.1.1
    subnet: 255.255.255.0

api:
  password: !secret api_password
  services:
    - service: control_stepper
      variables:
        target: int
      then:
        - stepper.set_target:
            id: my_stepper
            target: !lambda "return target;"

# Enable logging
logger:

ota:
  safe_mode: True
  password: !secret ota_password

text_sensor:
  - platform: version
    name: ${friendly_name} Version
    id: ${device_name}_version

sensor:
  - platform: wifi_signal
    name: ${friendly_name} Signal
    id: ${device_name}_signal
    update_interval: 60s
  - platform: template
    name: ${friendly_name} Position
    id: ${device_name}_position
    lambda: |-
      return id(my_stepper).current_position;

switch:
  - platform: template
    name: ${friendly_name} Reset
    id: ${device_name}_reset
    turn_on_action:
      - stepper.report_position:
          id: my_stepper
          position: 35000
    turn_off_action:
      - stepper.report_position:
          id: my_stepper
          position: 0

stepper:
  - platform: uln2003
    id: my_stepper
    pin_a: D1
    pin_b: D2
    pin_c: D3
    pin_d: D4
    max_speed: 250 steps/s
    sleep_when_done: true
    acceleration: 25
    deceleration: 25
