substitutions:
  device_name: bedroom_lamp
  friendly_name: Bedroom Lamp

esphomeyaml:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.241
    gateway: 192.168.1.1
    subnet: 255.255.255.0

api:
  password: !secret api_password

# mqtt:
#   broker: !secret mqtt_broker
#   username: !secret mqtt_username
#   password: !secret mqtt_password

# Enable logging
logger:

ota:
  safe_mode: True
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${friendly_name} Button
    id: ${device_name}_button
    on_press:
      then:
        - light.toggle: ${device_name}

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: ${device_name}
    name: $friendly_name
    output: relay