substitutions:
  device_name: bedroom_blind
  friendly_name: Bedroom Blind
  ip_address: 192.168.1.241

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  arduino_version: latest

<<: !include common.yaml

cover:
  - platform: template
    name: ${friendly_name}
    id: ${device_name}
    device_class: blind
    optimistic: true
    open_action:
      - stepper.set_target:
          id: my_stepper
          target: 0
    close_action:
      - stepper.set_target:
          id: my_stepper
          target: 35000

switch:
  - platform: template
    name: ${friendly_name} Set Closed
    id: ${device_name}_set_closed
    turn_on_action:
      - stepper.report_position:
          id: my_stepper
          position: 35000
  - platform: template
    name: ${friendly_name} Set Open
    id: ${device_name}_set_open
    turn_on_action:
      - stepper.report_position:
          id: my_stepper
          position: 0

stepper:
  - platform: uln2003
    id: my_stepper
    pin_a: D1
    pin_b: D2
    pin_c: D3
    pin_d: D4
    max_speed: 300 steps/s
    sleep_when_done: true
    acceleration: 25
    deceleration: 25
