substitutions:
  device_name: bedroom_lamp
  friendly_name: Bedroom Lamp
  ip_address: 192.168.1.244

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  arduino_version: latest

<<: !include common.yaml

status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${friendly_name} Button
    id: ${device_name}_button
    on_click:
      max_length: 250ms
      then:
        - light.toggle: ${device_name}

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: ${device_name}
    name: $friendly_name
    output: relay
