esphomeyaml:
  name: garage_door
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

ota:
  safe_mode: True
  password: !secret ota_password

switch:
  - platform: gpio
    pin: GPIO12
    id: relay

binary_sensor:
  - platform: gpio
    name: "Garage Door Switch"
    id: garage_door_switch
    pin: 
      number: GPIO14
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms

cover:
  - platform: template
    name: "Garage Door"
    lambda: !lambda |-
      if (id(garage_door_switch).state) {
        return cover::COVER_CLOSED;
      } else {
        return cover::COVER_OPEN;
      }
    open_action:
    - switch.turn_on: relay
    - delay: 100ms
    - switch.turn_off: relay
    close_action:
    - switch.turn_on: relay
    - delay: 100ms
    - switch.turn_off: relay