substitutions:
  device_name: kitchen_light_2
  device_friendly_name: Kitchen Light 2

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret ip_kitchen_light_2
    gateway: 192.168.1.1
    subnet: 255.255.255.0

api:
  password: !secret api_password

# Enable logging
logger:

ota:
  safe_mode: True
  password: !secret ota_password

text_sensor:
  - platform: version
    name: ${device_friendly_name} Version
    id: ${device_name}_version

sensor:
  - platform: wifi_signal
    name: ${device_friendly_name} Signal
    id: ${device_name}_signal
    update_interval: 60s

output:
  - platform: gpio
    id: relay_1
    pin: GPIO4

light:
  - platform: binary
    id: ${device_name}
    name: ${device_friendly_name}
    output: relay_1

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      # inverted: True
    name: ${device_friendly_name} Switch
    on_press:
      then:
        - light.toggle: ${device_name}
    on_release:
      then:
        - light.toggle: ${device_name}
