esphomeyaml:
  name: kitchen_lights
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  port: 8883
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Kitchen Lights Switch"
    on_press:
      then:
        - light.toggle: kitchen_lights
    on_release:
      then:
        - light.toggle: kitchen_lights

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: kitchen_lights
    name: "Kitchen Lights"
    output: relay