substitutions:
  device_name: kitchen_switch
  device_friendly_name: Kitchen Switch
  switch_1_name: lounge_light
  switch_1_friendly_name: Lounge Light
  switch_2_name: kitchen_light
  switch_2_friendly_name: Kitchen Light
  static_ip: 192.168.1.247

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${static_ip}
    gateway: 192.168.1.1
    subnet: 255.255.255.0

api:
  password: !secret api_password

# Enable logging
logger:

ota:
  safe_mode: True
  password: !secret ota_password

text_sensor:
  - platform: version
    name: ${device_friendly_name} Version
    id: ${device_name}_version

sensor:
  - platform: wifi_signal
    name: ${device_friendly_name} Signal
    id: ${device_name}_signal
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    name: ${switch_1_friendly_name} Button
    id: ${switch_1_name}_button
    on_press:
      then:
        - light.toggle: ${switch_1_name}
        - light.toggle: ${switch_1_name}_led
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: True
    name: ${switch_2_friendly_name} Button
    id: ${switch_2_name}_button
    on_press:
      then:
        - light.toggle: ${switch_2_name}
        - light.toggle: ${switch_2_name}_led

output:
  - platform: gpio
    id: relay_1
    pin: GPIO13
  - platform: gpio
    id: relay_2
    pin: GPIO15
  # Wifi Symbol
  - platform: esp8266_pwm
    id: ${device_name}_pwm
    pin: GPIO0
    inverted: True
  - platform: esp8266_pwm
    id: ${switch_1_name}_pwm
    pin: GPIO16
    inverted: True
  - platform: esp8266_pwm
    id: ${switch_2_name}_pwm
    pin: GPIO14
    inverted: True

light:
  - platform: binary
    id: ${switch_1_name}
    name: ${switch_1_friendly_name}
    output: relay_1
  - platform: binary
    id: ${switch_2_name}
    name: ${switch_2_friendly_name}
    output: relay_2
  - platform: monochromatic
    name: ${device_friendly_name} LED
    id: ${device_name}_led
    output: ${device_name}_pwm
  - platform: monochromatic
    name: ${switch_1_friendly_name} LED
    id: ${switch_1_name}_led
    output: ${switch_1_name}_pwm
  - platform: monochromatic
    name: ${switch_2_friendly_name} LED
    id: ${switch_2_name}_led
    output: ${switch_2_name}_pwm
