substitutions:
  device_name: right_garage
  friendly_name: Right Garage
  ip_address: 192.168.1.242

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  arduino_version: latest

<<: !include common.yaml

switch:
  - platform: gpio
    pin: GPIO12
    id: relay

binary_sensor:
  - platform: gpio
    name: ${friendly_name} Switch
    id: ${device_name}_switch
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms

cover:
  - platform: template
    name: ${friendly_name}
    id: ${device_name}
    device_class: garage
    lambda: !lambda |-
      if (id(${device_name}_switch).state) {
        return cover::COVER_CLOSED;
      } else {
        return cover::COVER_OPEN;
      }
    open_action:
      - switch.turn_on: relay
      - delay: 100ms
      - switch.turn_off: relay
    close_action:
      - switch.turn_on: relay
      - delay: 100ms
      - switch.turn_off: relay
