substitutions:
  device_name: right_garage
  friendly_name: Right Garage

esphomeyaml:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.243
    gateway: 192.168.1.1
    subnet: 255.255.255.0

api:
  password: !secret api_password

# Enable logging
logger:

ota:
  safe_mode: True
  password: !secret ota_password

text_sensor:
  - platform: version
    name: ${friendly_name} Version
    id: ${device_name}_version

switch:
  - platform: gpio
    pin: GPIO12
    id: relay

binary_sensor:
  - platform: gpio
    name: ${friendly_name} Switch
    id: ${device_name}_switch
    pin: 
      number: GPIO14
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms

cover:
  - platform: template
    name: ${friendly_name}
    id: ${device_name}
    lambda: !lambda |-
      if (id(${device_name}_switch).state) {
        return cover::COVER_CLOSED;
      } else {
        return cover::COVER_OPEN;
      }
    open_action:
    - switch.turn_on: relay
    - delay: 100ms
    - switch.turn_off: relay
    close_action:
    - switch.turn_on: relay
    - delay: 100ms
    - switch.turn_off: relay