esphomeyaml:
  name: shelly_1
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    name: "Shelly 1 Switch"
    on_press:
      then:
        - light.toggle: shelly_1
  - platform: status
    name: "Shelly 1 Status"

output:
  - platform: gpio
    id: relay
    pin: GPIO4

light:
  - platform: binary
    id: shelly_1
    name: "Shelly 1"
    output: relay