substitutions:
  device_name: study_lamp
  friendly_name: Study Lamp

esphomeyaml:
  name: ${device_name}
  platform: ESP8266
# Check the board type first!!!  
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.244
    gateway: 192.168.1.1
    subnet: 255.255.255.0

api:
  password: !secret api_password

# Enable logging
logger:

ota:
  safe_mode: True
  password: !secret ota_password

text_sensor:
  - platform: version
    name: ${friendly_name} Version
    id: ${device_name}_version

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Study Lamp Button"
    on_press:
      then:
        - light.toggle: study_lamp

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: study_lamp
    name: "Study Lamp"
    output: relay