esphomeyaml:
  name: study_lamp
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# mqtt:
#   broker: !secret mqtt_broker
#   username: !secret mqtt_username
#   password: !secret mqtt_password

api:
  password: !secret api_password

# Enable logging
logger:

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Study Lamp Button"
    on_press:
      then:
        - light.toggle: study_lamp

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: study_lamp
    name: "Study Lamp"
    output: relay