esphomeyaml:
  name: subaru_xv
  platform: ESP8266
  board: d1_mini
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  port: 8883
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

ota:
  password: !secret ota_password

binary_sensor:
  - platform: status
    device_class: presence
    name: "Subaru XV"