substitutions:
  device_name: ble_scanner
  friendly_name: BLE Scanner

esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret ip_ble_scanner
    gateway: 192.168.1.1
    subnet: 255.255.255.0

api:
  password: !secret api_password

# Enable logging
logger:

ota:
  safe_mode: True
  password: !secret ota_password

text_sensor:
  - platform: version
    name: ${friendly_name} Version
    id: ${device_name}_version

sensor:
  - platform: wifi_signal
    name: ${friendly_name} Signal
    id: ${device_name}_signal
    update_interval: 60s

binary_sensor:
  - platform: esp32_ble_tracker
    mac_address: F0:18:98:A3:26:7D
    name: Subaru XV
    id: subaru_xv

esp32_ble_tracker:
  scan_interval: 60s
# binary_sensor:
#   - platform: gpio
#     pin:
#       number: GPIO0
#       mode: INPUT_PULLUP
#       inverted: True
#     name: ${friendly_name} Button
#     id: ${device_name}_button
#     on_press:
#       then:
#         - light.toggle: ${device_name}

# output:
#   - platform: gpio
#     id: relay
#     pin: GPIO12

# light:
#   - platform: binary
#     id: ${device_name}
#     name: $friendly_name
#     output: relay
