wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

logger:
  level: INFO

ota:
  password: !secret ota_password

text_sensor:
  - platform: version
    name: ${friendly_name} espHome Version
    id: ${device_name}_esphome_version

sensor:
  - platform: wifi_signal
    name: ${friendly_name} Signal
    id: ${device_name}_signal
    update_interval: 60s
